# Generated by Django 4.0.3 on 2022-08-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='winery_id',
        ),
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='inventory.winery'),
        ),
    ]
