# FROM python:3.10-bullseye
# RUN python -m pip install --upgrade pip
# WORKDIR /app

# COPY poll/requirements.txt requirements.txt
# COPY poll/poller.py poller.py

# COPY sales sales
# COPY sales_rest sales_rest
# COPY common common

# RUN pip install -r requirements.txt
# CMD python poller.py