# Generated by Django 4.0.3 on 2022-08-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WineryVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('import_href', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WineVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=110)),
                ('year', models.SmallIntegerField()),
                ('varietal', models.CharField(max_length=110)),
                ('description', models.TextField(null=True)),
                ('region', models.CharField(max_length=110, null=True)),
                ('abv', models.FloatField()),
                ('volume', models.SmallIntegerField()),
                ('city_state', models.CharField(max_length=110, null=True)),
                ('price', models.FloatField()),
                ('picture_url', models.URLField(max_length=220, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('import_href', models.CharField(max_length=200, unique=True)),
                ('winery_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='sales_rest.wineryvo')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_items', to='sales_rest.winevo')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_items', to='sales_rest.order')),
            ],
        ),
    ]
