# Generated by Django 4.0.3 on 2022-08-23 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='active',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmation_number',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='sales_rest.order'),
        ),
        migrations.AlterField(
            model_name='winevo',
            name='winery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='sales_rest.wineryvo'),
        ),
    ]
