# Generated by Django 4.0.3 on 2022-09-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='winevo',
            name='city_state',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='winevo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winevo',
            name='picture_url',
            field=models.URLField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='winevo',
            name='region',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
