# Generated by Django 4.0.3 on 2022-08-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_shoppingitem_active_shoppingitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winevo',
            name='winery_id',
            field=models.SmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='WineryVO',
        ),
    ]
