# Generated by Django 4.0.3 on 2022-09-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0004_remove_shoppingitem_user_order_address_one_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="account_email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
